env:
  browser: true
  es2020: true
  jest: true
extends:
  - 'airbnb-base'
  - plugin:jest-dom/recommended
  - plugin:testing-library/dom
plugins:
  - 'testing-library'
  - 'jest-dom'
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  import/extensions: 0
  import/no-import-module-exports: 0
  no-console: 0
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
